# Generated by Django 4.0.3 on 2022-04-15 20:37

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('useremail', models.EmailField(max_length=30)),
                ('userage', models.CharField(max_length=2)),
                ('bio', models.CharField(max_length=100)),
                ('profile_image', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='images')),
                ('user_password', models.CharField(max_length=15)),
            ],
        ),
    ]
